### PR TITLE
Add github stars badge

### PR DESCRIPTION
**Pull request by theo-m**
Hey just did a quick batch editing to see star count on repos as it's helpful to flag attempts that are "validated" by the community.

Result of this PR is visible in my fork: https://github.com/theo-m/awesome-advent-of-code

Also added language badge since it was easy to do and I've been surprised by some of the labelling (e.g. one golang repos was actually python code).

### CODE REVIEW

**Comment by Bogdanp** [comment]
Thanks, but they'll become outdated unless this is automated, and the action that updates the badges will just remove them anyway. If you want to automate this stuff, then look at the action code in `.github/actions/update-badge`.

**Comment by theo-m** [comment]
I don't think it's cached, see the network activity: Screenshot 2021-12-07 at 18 12 04

**Comment by Bogdanp** [comment]
Thanks, yeah, I missed that these weren't static. The fact that they'll be removed by the action still stands, though.

**Comment by theo-m** [comment]
oh yeah shame 
from shields.io documentation it seems you could use their api directly rather than rely on actions? (https://shields.io/category/activity)

I have not looked at your actions thoroughly, maybe they do more than compute last commit date

**Pull request closed without merging**
