### PR TITLE
Update 2019.md

### PR DESCRIPTION
**Pull request by Praful**
added Dart 2019 repos

### CODE REVIEW

**Comment by Bogdanp** [comment]
The only change I see here is an added newline.

**Comment by Praful** [comment]
Although my repo [Praful/advent_of_code] is under Dart it doesn't appear as a link. So I added a newline but perhaps there's another reason?

**Comment by Bogdanp** [comment]
The archived docs don't get updated automatically, so you're going to have to format the link yourself if you want.

**Comment by Bogdanp** [comment]
I've closed this to get it off my PR list, but feel free to make a new PR if you want to manually format your link.

**Pull request closed without merging**
